### ISSUE TITLE
Inconsistent mode switching when using different scroll methods

### ISSUE THREAD

**Issue by mdingena** [codecks-io/react-sticky-box#26] opened 2018-10-30 12:41 UTC
After upgrading to `0.7.5` to fix #16, I ran a couple of tests and noticed that [the "deadzone" issue](https://github.com/codecks-io/react-sticky-box/pull/18#issue-217745088) is back (probably caused by the code changes from #25).

Upon further inspecting, I noticed that StickyBox behaves differently when dragging the scrollbar or when using the mouse wheel. I did that because I wanted to better inspect the "deadzone", a situation where you scroll in a direction but StickyBox remains sticky for some pixels.

Here's a screen recording of this behavior. Both sidebars are StickyBoxes.

https://i.imgur.com/3Zikt7b.gifv

**Comment by danielberndt** [comment] 2018-11-04 16:30
I just tried to reproduce the issue, and wasn't very successful. Which OS and Browser are you using? I just tried Chrome, Firefox and Safari on OSX on some sample pages and couldn't find this behaviour.

Does it happen on all of your pages? Or just the very heavy ones with hundreds of DOM elements? 
I found that browsers sometimes still have issues even when using only a css `position: sticky` layout on some large pages.

**Comment by mdingena** [comment] 2018-11-05 07:34
I've been using Windows 7 (64-bit) and Windows 10 (64-bit), both using Google Chrome Version 70.0.3538.77 (Official Build) (64-bit).

I've only been able to test this on the Search page of my app, because that's currently one of the few features that it supports. There is an individual post page where a single sidebar is a StickyBox, but I haven't tested it there yet. I wouldn't call the Search page very heavy, but it does support endless scrolling, so it could potentially get heavy.

While it's not very hard to reproduce for me, I can't really put my finger on what exactly is causing it, because it seems like a mix of issues. Unfortunately, I'm currently tied up in emigration so I have very little time to work on this hobby project at the moment. Would you mind leaving this issue open? I will come back to it and give you more details when I find the time in a few weeks.

**Comment by danielberndt** [comment] 2022-03-06 16:28
closing this issue due to its age

**Closed by danielberndt** 2022-03-06 16:28 UTC
